export { default as Communication } from './Communication'
export { default as Development } from './Development'
export { default as Hero } from './Hero'
export { default as Service } from './Service'
export { default as Technology } from './Technology'
