export const LOTTERY_COST_PER_TICKET_REFRESH_INTERVAL_MS = 0
export const LOTTERY_PRIZE_POOL_REFRESH_INTERVAL_MS = 20000
export const LOTTERY_STATUS_REFRESH_INTERVAL_MS = 30000
export const LotteryStatus = {
  NOT_STARTED: 0,
  OPEN: 1,
  CLOSED: 2,
  COMPLETED: 3,
}
